### ISSUE TITLE
Chroot and Nexmon

### ISSUE THREAD

**Issue by AutinDroid** [seemoo-lab/bcm-public#5]
If I wanted to make nexmon work in Chroot, I just need to apply the patch from https://github.com/seemoo-lab/bcm-public/blob/90bed6e1c3ad70ddc23ccf44033b152e0db300b6/kernel_patches/40mhz_channels_5GHz.patch ?

**Comment by AutinDroid** [comment]
I have replaced my wl_cfg80211 with the one from this respiratory, but now Airodump-ng crashes the phone when scanning with wlan0.

**Comment by nethunteros** [comment]
I applied first patch you mentioned and this patch: https://github.com/nethunteros/android_kernel_lge_hammerhead/commit/d32bedee33b4808c82669adc4ae1e3ba6a6b263c.

You also have to recompile libfakeioctl.so if you want the native airodump-ng to work.  I attached a copy earlier also: https://github.com/seemoo-lab/bcm-public/files/608093/libfakeioctl.zip

You just have to export LD_PRELOAD=libfakeioctl.so after that.

**Comment by AutinDroid** [comment]
@nethunteros I have the libfakeioctlkali.so and monstart-nh installed in my ROM. Is that good enough?

**Comment by nethunteros** [comment]
Yes, if you already have the precompile library you just need to access it from chroot.  You also need to make sure you have the nexmon firmware for wifi.

**Comment by AutinDroid** [comment]
I have all that. So all I need to do is just compile the kernel with your wl_cfg80211 or do I need to patch the stock driver?

**Comment by nethunteros** [comment]
For the kernel you just need the two patches.  This worked for me:

https://github.com/nethunteros/android_kernel_lge_hammerhead/commit/e5cca67d78166c0054a2d0a928d0e571bac20893
https://github.com/nethunteros/android_kernel_lge_hammerhead/commit/d32bedee33b4808c82669adc4ae1e3ba6a6b263c

**Comment by AutinDroid** [comment]
@nethutneros I applied all the patches and airodump-ng is not crashing. My problem is now that airodump-ng is not showing any routers.

**Comment by AutinDroid** [comment]
I fixed the problem (I was dumb and forgot to install the nexmon firmware). Unfortunately, after the patch, I can't seem to use the play store (never loads). That's odd...

**Comment by AutinDroid** [comment]
Fixed it by wiping play store data and cache.
